import React from 'react';
import { cn } from '@/lib/utils';

export type DisclaimerVariant = 'A' | 'B' | 'C' | 'D' | 'E';

interface DisclaimerBlockProps {
  variant: DisclaimerVariant;
  className?: string;
  headingClassName?: string;
}

export const DISCLAIMER_B_TEXT =
  "This report is generated by PropPath, a planning and visualisation tool used by buyers' agents. The information shown is factual modelling based on inputs provided and does not take into account your specific objectives, financial situation, or needs. It is not financial, credit, mortgage, or tax advice - speak to an appropriately licensed adviser before making any decision based on it.";

export const DISCLAIMER_C_LINE_1 =
  'Factual information only. Not financial, credit, or tax advice.';

export const DISCLAIMER_C_LINE_2 =
  'Inputs and projections are estimates - see full disclaimer.';

export const DISCLAIMER_C_TEXT = `${DISCLAIMER_C_LINE_1} ${DISCLAIMER_C_LINE_2}`;

export const DISCLAIMER_D_TEXT =
  'PropPath provides factual modelling, not financial or credit advice.';

export const DISCLAIMER_E_TEXT =
  'PropPath is not designed for self-managed super fund (SMSF) property strategies. SMSF property purchases require an Australian Financial Services Licence and are outside the intended use of this tool. By continuing, you confirm you will not use PropPath to model or present SMSF property strategies to clients.';

export const DISCLAIMER_A_HEADING = 'Disclaimers and Important Information';

export const DISCLAIMER_A_CLAUSES: string[] = [
  'PropPath is a planning and visualisation tool. It is not a licensed financial adviser, mortgage broker, tax adviser, accountant, or bookkeeper. PropPath does not hold an Australian Financial Services Licence (AFSL) or an Australian Credit Licence (ACL).',
  'Information provided by PropPath - including projections, scenarios, timelines, dashboards, charts, summaries, and AI-generated narratives - is factual information only. It does not constitute financial product advice, credit assistance, or any recommendation tailored to a specific person\'s objectives, financial situation, or needs.',
  'Users should seek advice from a licensed financial adviser before making any decision that may involve a financial product, including superannuation, managed investments, or insurance.',
  'Users should seek advice from a licensed mortgage broker or credit provider before applying for, refinancing, varying, or relying on any loan, equity release, or credit facility.',
  'Users should seek advice from a registered tax agent or accountant before relying on any projection of tax outcomes, deductions, depreciation, capital gains, land tax, or stamp duty.',
  'Forecasts, projections, growth rates, rental yields, and price assumptions shown in PropPath are estimates based on user-entered inputs and default parameters. They assume no major macroeconomic shocks, no significant legislative changes, and that user inputs are accurate. Past performance is not a guarantee of future results, and all property investment carries risk including loss of capital.',
  'Property is generally an illiquid, long-term asset class. Market values, rental income, vacancy, and holding costs can vary materially from any estimate shown by PropPath.',
  'PropPath is designed for use by licensed Australian buyers\' agents modelling residential and commercial property scenarios for their clients. PropPath is NOT designed for, and should not be used in connection with, self-managed superannuation fund (SMSF) property purchases, limited recourse borrowing arrangements (LRBA), or any superannuation-related strategy. Such matters require a separate AFSL and are outside the intended use of this tool.',
  'Where a buyers\' agent presents PropPath outputs to their client, the buyers\' agent is responsible for ensuring they hold the appropriate state real estate licence and that any advice they provide is within the scope of that licence.',
  'To the maximum extent permitted by law, PropPath, its operators, and its partners disclaim all liability for any decision made, action taken, or loss suffered in reliance on information shown by the tool. Nothing in this disclaimer is intended to limit any rights you have under the Australian Consumer Law that cannot be excluded.',
];

export function DisclaimerBlock({
  variant,
  className,
  headingClassName,
}: DisclaimerBlockProps) {
  switch (variant) {
    case 'A':
      return (
        <section className={cn('text-sm text-gray-700 leading-relaxed', className)}>
          <h2
            className={cn(
              'text-xl font-semibold text-gray-900 mb-4',
              headingClassName,
            )}
          >
            {DISCLAIMER_A_HEADING}
          </h2>
          <ol className="list-decimal pl-5 space-y-3">
            {DISCLAIMER_A_CLAUSES.map((clause, i) => (
              <li key={i}>{clause}</li>
            ))}
          </ol>
        </section>
      );

    case 'B':
      return (
        <p
          className={cn(
            'text-xs text-gray-500 italic leading-relaxed max-w-2xl',
            className,
          )}
        >
          {DISCLAIMER_B_TEXT}
        </p>
      );

    case 'C':
      return (
        <div
          className={cn(
            'text-[10px] text-gray-400 leading-relaxed text-center',
            className,
          )}
        >
          <p>{DISCLAIMER_C_LINE_1}</p>
          <p>{DISCLAIMER_C_LINE_2}</p>
        </div>
      );

    case 'D':
      return (
        <p className={cn('text-[11px] text-gray-500 italic', className)}>
          {DISCLAIMER_D_TEXT}
        </p>
      );

    case 'E':
      return (
        <div
          className={cn(
            'rounded-md border border-amber-200 bg-amber-50 p-3',
            className,
          )}
          role="note"
        >
          <p className="text-xs text-amber-900 leading-relaxed">
            {DISCLAIMER_E_TEXT}
          </p>
        </div>
      );

    default: {
      const _exhaustive: never = variant;
      return null;
    }
  }
}

export default DisclaimerBlock;
