// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gaoqzrdzihmrwipwsbwo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdhb3F6cmR6aWhtcndpcHdzYndvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg5MTk2MDQsImV4cCI6MjA3NDQ5NTYwNH0.PcoSky4H-rC3D7FqpNHUrVGeqTx52cfmRawqm1DBxsM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});